#!/bin/bash
myFunction(){
  for i in $(cut -d' ' -f1 $HOME/.favoris_bash); do
    if [[ $i = $2  ]]; then
      let "count++";
      if [[ $option = "C" ]]; then
        break;
      fi
    fi
    if [[ $option = "C" ]]; then
      let nbr_itration++
    fi
  done
  if [[ $count -eq 0 ]]; then
    if [[ $option = "S" ]]; then
      echo  $2 '->' $PWD >> $HOME/.favoris_bash
    fi
    if [[ $option = "C" ]]; then
      echo "favoris dont exist"
    fi
  else
    if [[ $option = "S" ]]; then
      echo 'exist a favoris with this name change a name of your favoris'
    fi
    if [[ $option = "C" ]]; then
      path=`head -$nbr_itration $HOME/.favoris_bash | tail -1|cut -d'>' -f2`
      cd $path
      echo "you are in $path"
    fi
  fi
}

Myhelp(){
  printf "\e[38;5;046m
        ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
        ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
        ::::                                                                                                    ::::
        ::::         ::    ::    ::::::      ::          :::::::     ths options of this command:               ::::
        ::::         ::    ::    ::          ::          ::    ::    use like this source favoris Option        ::::
        ::::         ::::::::    ::::::      ::          :::::::     L : show list of favoris                   ::::
        ::::         ::    ::    ::          ::          ::          S : add new favoris                        ::::
        ::::         ::    ::    ::::::      ::::::::    ::          C : go to favoris                          ::::
        ::::                                                         R : remove favoris                         ::::
        ::::                                                         -h: show help for this command             ::::
        ::::                                                         -u: unstall this command                   ::::
        ::::                                                                                                    ::::
        ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
        ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
        \n"
}

touch $HOME/.favoris_bash



case $1 in

    "S" )
          count=0
          option="S"
          myFunction $count $2 $option
    ;;

    "C")
        count=0
        nbr_itration=1;
        option="C"
        myFunction $count $2 $option $nbr_itration
    ;;
    "L")
      echo "favoris List :"
      echo "-------------------------------"
      cut -d' ' -f1 $HOME/.favoris_bash
      echo "-------------------------------"
    ;;
    "R")
    nbr_itration=1
    count=0
    touch $HOME/.favoris_bash1
    for i in $(cut -d' ' -f1 $HOME/.favoris_bash); do
      line=`head -$nbr_itration $HOME/.favoris_bash | tail -1`
      if [[ $i != $2  ]]; then
        echo $line >> $HOME/.favoris_bash1
      else
        let count++
      fi
      let nbr_itration++
    done
    if [[ $count -eq 0 ]]; then
      echo "favorsi don't exist"
      rm $HOME/.favoris_bash1
    else
      rm $HOME/.favoris_bash
      mv $HOME/.favoris_bash1 $HOME/.favoris_bash
    fi
    ;;
    "-h")
     Myhelp
    ;;

esac
